# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 665)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralWidget)
        self.tabs.setEnabled(True)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setDocumentMode(False)
        self.tabs.setObjectName("tabs")
        self.chemshiftTab = QtWidgets.QWidget()
        self.chemshiftTab.setEnabled(True)
        self.chemshiftTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.chemshiftTab.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.chemshiftTab.setObjectName("chemshiftTab")
        self.chemshiftTabLayout = QtWidgets.QGridLayout(self.chemshiftTab)
        self.chemshiftTabLayout.setContentsMargins(11, 11, 11, 11)
        self.chemshiftTabLayout.setHorizontalSpacing(25)
        self.chemshiftTabLayout.setVerticalSpacing(6)
        self.chemshiftTabLayout.setObjectName("chemshiftTabLayout")
        self.cutoffSpinBox = QtWidgets.QDoubleSpinBox(self.chemshiftTab)
        self.cutoffSpinBox.setObjectName("cutoffSpinBox")
        self.chemshiftTabLayout.addWidget(self.cutoffSpinBox, 1, 1, 1, 1)
        self.stepSlider = QtWidgets.QSlider(self.chemshiftTab)
        self.stepSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stepSlider.setMinimum(1)
        self.stepSlider.setMaximum(10)
        self.stepSlider.setTracking(True)
        self.stepSlider.setOrientation(QtCore.Qt.Vertical)
        self.stepSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.stepSlider.setObjectName("stepSlider")
        self.chemshiftTabLayout.addWidget(self.stepSlider, 0, 0, 1, 1)
        self.stepLabel = QtWidgets.QLabel(self.chemshiftTab)
        self.stepLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLabel.setObjectName("stepLabel")
        self.chemshiftTabLayout.addWidget(self.stepLabel, 1, 0, 1, 1)
        self.cutoffSlider = QtWidgets.QSlider(self.chemshiftTab)
        self.cutoffSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cutoffSlider.setSliderPosition(0)
        self.cutoffSlider.setOrientation(QtCore.Qt.Vertical)
        self.cutoffSlider.setInvertedAppearance(False)
        self.cutoffSlider.setObjectName("cutoffSlider")
        self.chemshiftTabLayout.addWidget(self.cutoffSlider, 0, 1, 1, 1)
        self.widget_2 = QChartView(self.chemshiftTab)
        self.widget_2.setObjectName("widget_2")
        self.chemshiftTabLayout.addWidget(self.widget_2, 0, 2, 1, 1)
        self.tabs.addTab(self.chemshiftTab, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setEnabled(True)
        self.tab2.setObjectName("tab2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabs.addTab(self.tab2, "")
        self.protocoleTab = QtWidgets.QWidget()
        self.protocoleTab.setObjectName("protocoleTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.protocoleTab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_3.setSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtWidgets.QTableView(self.protocoleTab)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 0, 1, 1, 1)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.protocoleTab)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_3.addWidget(self.graphicsView_5, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.protocoleTab)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(9, 11, 15, 11)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_6.setContentsMargins(20, 20, 20, 20)
        self.formLayout_6.setSpacing(6)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.analyteVolumeLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.analyteVolumeLabel_2.setObjectName("analyteVolumeLabel_2")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.analyteVolumeLabel_2)
        self.analyteVolumeDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.analyteVolumeDoubleSpinBox_2.setObjectName("analyteVolumeDoubleSpinBox_2")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.analyteVolumeDoubleSpinBox_2)
        self.totalVolumeLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.totalVolumeLabel_2.setObjectName("totalVolumeLabel_2")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.totalVolumeLabel_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.step0Label = QtWidgets.QLabel(self.groupBox_2)
        self.step0Label.setObjectName("step0Label")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.step0Label)
        self.step0SpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.step0SpinBox.setEnabled(False)
        self.step0SpinBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.step0SpinBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.step0SpinBox.setObjectName("step0SpinBox")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.step0SpinBox)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.verticalLayout_5.addLayout(self.formLayout_6)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.analyteLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.analyteLabel_3.setObjectName("analyteLabel_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.analyteLabel_3)
        self.analyteLineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.analyteLineEdit_3.setObjectName("analyteLineEdit_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analyteLineEdit_3)
        self.mLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.mLabel_3.setObjectName("mLabel_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mLabel_3)
        self.mSpinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.mSpinBox_3.setObjectName("mSpinBox_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mSpinBox_3)
        self.horizontalLayout_6.addLayout(self.formLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setSpacing(6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.analyteLabel_4 = QtWidgets.QLabel(self.groupBox)
        self.analyteLabel_4.setObjectName("analyteLabel_4")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.analyteLabel_4)
        self.analyteLineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.analyteLineEdit_4.setObjectName("analyteLineEdit_4")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analyteLineEdit_4)
        self.mLabel_4 = QtWidgets.QLabel(self.groupBox)
        self.mLabel_4.setObjectName("mLabel_4")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mLabel_4)
        self.mSpinBox_4 = QtWidgets.QSpinBox(self.groupBox)
        self.mSpinBox_4.setObjectName("mSpinBox_4")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mSpinBox_4)
        self.horizontalLayout_6.addLayout(self.formLayout_5)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.tabs.addTab(self.protocoleTab, "")
        self.horizontalLayout.addWidget(self.tabs)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1162, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("exit")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.stepSlider.valueChanged['int'].connect(self.stepLabel.setNum)
        self.actionNew.triggered.connect(MainWindow.setup)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stepSlider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set titration step to view chemical shifts variations</p></body></html>"))
        self.stepLabel.setText(_translate("MainWindow", "0"))
        self.cutoffSlider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set cut-off</p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.chemshiftTab), _translate("MainWindow", "Chemical Shifts"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab2), _translate("MainWindow", "Page"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Volumes (µL)"))
        self.label.setText(_translate("MainWindow", "Initial"))
        self.analyteVolumeLabel_2.setText(_translate("MainWindow", "Analyte"))
        self.totalVolumeLabel_2.setText(_translate("MainWindow", "Total"))
        self.label_2.setText(_translate("MainWindow", "Added"))
        self.step0Label.setText(_translate("MainWindow", "Step 0"))
        self.groupBox.setTitle(_translate("MainWindow", "Stock solutions"))
        self.analyteLabel_3.setText(_translate("MainWindow", "Analyte"))
        self.analyteLineEdit_3.setPlaceholderText(_translate("MainWindow", "Name"))
        self.mLabel_3.setText(_translate("MainWindow", "[µM]"))
        self.analyteLabel_4.setText(_translate("MainWindow", "Titrant"))
        self.analyteLineEdit_4.setPlaceholderText(_translate("MainWindow", "Name"))
        self.mLabel_4.setText(_translate("MainWindow", "[µM]"))
        self.tabs.setTabText(self.tabs.indexOf(self.protocoleTab), _translate("MainWindow", "Protocole"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New experiment"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

from PyQt5.QtChart import QChartView
