# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 683)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralWidget)
        self.tabs.setEnabled(True)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setDocumentMode(False)
        self.tabs.setObjectName("tabs")
        self.chemshiftTab = QtWidgets.QWidget()
        self.chemshiftTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chemshiftTab.sizePolicy().hasHeightForWidth())
        self.chemshiftTab.setSizePolicy(sizePolicy)
        self.chemshiftTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.chemshiftTab.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.chemshiftTab.setObjectName("chemshiftTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.chemshiftTab)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtWidgets.QSplitter(self.chemshiftTab)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(8)
        self.splitter.setObjectName("splitter")
        self.graphContainer = QtWidgets.QWidget(self.splitter)
        self.graphContainer.setObjectName("graphContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.graphContainer)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sliders_layout = QtWidgets.QGridLayout()
        self.sliders_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.sliders_layout.setSpacing(6)
        self.sliders_layout.setObjectName("sliders_layout")
        self.label_4 = QtWidgets.QLabel(self.graphContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.sliders_layout.addWidget(self.label_4, 1, 1, 1, 1)
        self.cutoffSpinBox = QtWidgets.QDoubleSpinBox(self.graphContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutoffSpinBox.sizePolicy().hasHeightForWidth())
        self.cutoffSpinBox.setSizePolicy(sizePolicy)
        self.cutoffSpinBox.setWrapping(False)
        self.cutoffSpinBox.setFrame(True)
        self.cutoffSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cutoffSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.cutoffSpinBox.setAccelerated(True)
        self.cutoffSpinBox.setProperty("showGroupSeparator", False)
        self.cutoffSpinBox.setDecimals(1)
        self.cutoffSpinBox.setSingleStep(0.5)
        self.cutoffSpinBox.setObjectName("cutoffSpinBox")
        self.sliders_layout.addWidget(self.cutoffSpinBox, 3, 1, 1, 1)
        self.stepLabel = QtWidgets.QLabel(self.graphContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stepLabel.setFont(font)
        self.stepLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLabel.setObjectName("stepLabel")
        self.sliders_layout.addWidget(self.stepLabel, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.graphContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.sliders_layout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.cutoffSlider = QtWidgets.QSlider(self.graphContainer)
        self.cutoffSlider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.cutoffSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cutoffSlider.setPageStep(10)
        self.cutoffSlider.setProperty("value", 0)
        self.cutoffSlider.setSliderPosition(0)
        self.cutoffSlider.setOrientation(QtCore.Qt.Vertical)
        self.cutoffSlider.setInvertedAppearance(False)
        self.cutoffSlider.setObjectName("cutoffSlider")
        self.sliders_layout.addWidget(self.cutoffSlider, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.stepSlider = QtWidgets.QSlider(self.graphContainer)
        self.stepSlider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.stepSlider.setMouseTracking(False)
        self.stepSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stepSlider.setMinimum(1)
        self.stepSlider.setMaximum(10)
        self.stepSlider.setTracking(True)
        self.stepSlider.setOrientation(QtCore.Qt.Vertical)
        self.stepSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.stepSlider.setTickInterval(1)
        self.stepSlider.setObjectName("stepSlider")
        self.sliders_layout.addWidget(self.stepSlider, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.sliders_layout)
        self.chartview = QChartView(self.graphContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chartview.sizePolicy().hasHeightForWidth())
        self.chartview.setSizePolicy(sizePolicy)
        self.chartview.setObjectName("chartview")
        self.horizontalLayout_3.addWidget(self.chartview)
        self.label_2 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.tabs.addTab(self.chemshiftTab, "")
        self.protocoleTab = QtWidgets.QWidget()
        self.protocoleTab.setObjectName("protocoleTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.protocoleTab)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.protocoleTab)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setSpacing(6)
        self.formLayout_6.setObjectName("formLayout_6")
        self.analyteVolumeLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.analyteVolumeLabel_2.setObjectName("analyteVolumeLabel_2")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.analyteVolumeLabel_2)
        self.analyteInitialVolume = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.analyteInitialVolume.setPrefix("")
        self.analyteInitialVolume.setMinimum(1.0)
        self.analyteInitialVolume.setObjectName("analyteInitialVolume")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analyteInitialVolume)
        self.totalVolumeLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.totalVolumeLabel_2.setObjectName("totalVolumeLabel_2")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.totalVolumeLabel_2)
        self.totalInitialVolume = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.totalInitialVolume.setMinimum(1.0)
        self.totalInitialVolume.setObjectName("totalInitialVolume")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.totalInitialVolume)
        self.verticalLayout_5.addLayout(self.formLayout_6)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.concChartView = QChartView(self.protocoleTab)
        self.concChartView.setMinimumSize(QtCore.QSize(50, 0))
        self.concChartView.setObjectName("concChartView")
        self.gridLayout.addWidget(self.concChartView, 2, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.protocoleTab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.analyteLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.analyteLabel_3.setObjectName("analyteLabel_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.analyteLabel_3)
        self.analyteName = QtWidgets.QLineEdit(self.groupBox)
        self.analyteName.setMaxLength(20)
        self.analyteName.setObjectName("analyteName")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analyteName)
        self.mLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.mLabel_3.setObjectName("mLabel_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mLabel_3)
        self.analyteConc = QtWidgets.QSpinBox(self.groupBox)
        self.analyteConc.setAccelerated(True)
        self.analyteConc.setMinimum(1)
        self.analyteConc.setObjectName("analyteConc")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.analyteConc)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setSpacing(6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.analyteLabel_4 = QtWidgets.QLabel(self.groupBox)
        self.analyteLabel_4.setObjectName("analyteLabel_4")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.analyteLabel_4)
        self.titrantName = QtWidgets.QLineEdit(self.groupBox)
        self.titrantName.setMaxLength(20)
        self.titrantName.setObjectName("titrantName")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titrantName)
        self.mLabel_4 = QtWidgets.QLabel(self.groupBox)
        self.mLabel_4.setObjectName("mLabel_4")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mLabel_4)
        self.titrantConc = QtWidgets.QSpinBox(self.groupBox)
        self.titrantConc.setAccelerated(True)
        self.titrantConc.setMinimum(1)
        self.titrantConc.setObjectName("titrantConc")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.titrantConc)
        self.horizontalLayout_2.addLayout(self.formLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.volumeChartView = QChartView(self.protocoleTab)
        self.volumeChartView.setObjectName("volumeChartView")
        self.gridLayout.addWidget(self.volumeChartView, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addStepBtn = QtWidgets.QPushButton(self.protocoleTab)
        self.addStepBtn.setAutoDefault(False)
        self.addStepBtn.setDefault(False)
        self.addStepBtn.setFlat(False)
        self.addStepBtn.setObjectName("addStepBtn")
        self.horizontalLayout_4.addWidget(self.addStepBtn)
        self.removeStepBtn = QtWidgets.QPushButton(self.protocoleTab)
        self.removeStepBtn.setObjectName("removeStepBtn")
        self.horizontalLayout_4.addWidget(self.removeStepBtn)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.protocoleTable = QtWidgets.QTableView(self.protocoleTab)
        self.protocoleTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.protocoleTable.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.protocoleTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.protocoleTable.setGridStyle(QtCore.Qt.DashLine)
        self.protocoleTable.setObjectName("protocoleTable")
        self.protocoleTable.horizontalHeader().setCascadingSectionResizes(False)
        self.protocoleTable.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.protocoleTable, 1, 0, 2, 2)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 10)
        self.gridLayout.setRowStretch(2, 10)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.manageStockBtn = QtWidgets.QPushButton(self.protocoleTab)
        self.manageStockBtn.setObjectName("manageStockBtn")
        self.verticalLayout_2.addWidget(self.manageStockBtn)
        self.analyteComboBox = QtWidgets.QComboBox(self.protocoleTab)
        self.analyteComboBox.setObjectName("analyteComboBox")
        self.analyteComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.analyteComboBox)
        self.titrantComboBox = QtWidgets.QComboBox(self.protocoleTab)
        self.titrantComboBox.setObjectName("titrantComboBox")
        self.titrantComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.titrantComboBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabs.addTab(self.protocoleTab, "")
        self.horizontalLayout.addWidget(self.tabs)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1162, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("exit")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionStock_solutions = QtWidgets.QAction(MainWindow)
        self.actionStock_solutions.setObjectName("actionStock_solutions")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionStock_solutions)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.analyteComboBox.setCurrentIndex(-1)
        self.titrantComboBox.setCurrentIndex(-1)
        self.actionNew.triggered.connect(MainWindow.setup)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionStock_solutions.triggered.connect(MainWindow.edit_stock)
        self.manageStockBtn.clicked.connect(MainWindow.edit_stock)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Cut-off"))
        self.stepLabel.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Step"))
        self.cutoffSlider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set cut-off</p></body></html>"))
        self.cutoffSlider.setStatusTip(_translate("MainWindow", "Cut-off"))
        self.stepSlider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set titration step to view chemical shifts variations</p></body></html>"))
        self.stepSlider.setStatusTip(_translate("MainWindow", "Step"))
        self.label_2.setText(_translate("MainWindow", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))
        self.tabs.setTabText(self.tabs.indexOf(self.chemshiftTab), _translate("MainWindow", "Chemical Shifts"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Initial Volumes (µL)"))
        self.analyteVolumeLabel_2.setText(_translate("MainWindow", "Analyte"))
        self.analyteInitialVolume.setSuffix(_translate("MainWindow", " µL"))
        self.totalVolumeLabel_2.setText(_translate("MainWindow", "Total"))
        self.totalInitialVolume.setSuffix(_translate("MainWindow", " µL"))
        self.groupBox.setTitle(_translate("MainWindow", "Stock solutions"))
        self.analyteLabel_3.setText(_translate("MainWindow", "Analyte"))
        self.analyteName.setPlaceholderText(_translate("MainWindow", "Analyte"))
        self.mLabel_3.setText(_translate("MainWindow", "Concentration"))
        self.analyteConc.setSuffix(_translate("MainWindow", " µM"))
        self.analyteLabel_4.setText(_translate("MainWindow", "Titrant"))
        self.titrantName.setPlaceholderText(_translate("MainWindow", "Titrant"))
        self.mLabel_4.setText(_translate("MainWindow", "Concentration"))
        self.titrantConc.setSuffix(_translate("MainWindow", " µM"))
        self.addStepBtn.setText(_translate("MainWindow", "Add Step"))
        self.removeStepBtn.setText(_translate("MainWindow", "Remove Step"))
        self.manageStockBtn.setText(_translate("MainWindow", "Manage stock solutions"))
        self.analyteComboBox.setItemText(0, _translate("MainWindow", "New Stock Solution"))
        self.titrantComboBox.setItemText(0, _translate("MainWindow", "New Stock Solution"))
        self.tabs.setTabText(self.tabs.indexOf(self.protocoleTab), _translate("MainWindow", "Protocole"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New experiment"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionStock_solutions.setText(_translate("MainWindow", "Stock solutions"))

from PyQt5.QtChart import QChartView
