# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/setupdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(801, 572)
        Dialog.setAutoFillBackground(False)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 7, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formWidget = QtWidgets.QWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.formWidget.setFont(font)
        self.formWidget.setObjectName("formWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout_3.setObjectName("formLayout_3")
        self.protonLabel = QtWidgets.QLabel(self.formWidget)
        self.protonLabel.setObjectName("protonLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.protonLabel)
        self.protonColumn = QtWidgets.QComboBox(self.formWidget)
        self.protonColumn.setEnabled(False)
        self.protonColumn.setObjectName("protonColumn")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.protonColumn)
        self.nitrogenLabel = QtWidgets.QLabel(self.formWidget)
        self.nitrogenLabel.setObjectName("nitrogenLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nitrogenLabel)
        self.nitrogenColumn = QtWidgets.QComboBox(self.formWidget)
        self.nitrogenColumn.setEnabled(False)
        self.nitrogenColumn.setObjectName("nitrogenColumn")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nitrogenColumn)
        self.residuLabel = QtWidgets.QLabel(self.formWidget)
        self.residuLabel.setObjectName("residuLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.residuLabel)
        self.residueColumn = QtWidgets.QComboBox(self.formWidget)
        self.residueColumn.setEnabled(False)
        self.residueColumn.setObjectName("residueColumn")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.residueColumn)
        self.headerCheckbox = QtWidgets.QCheckBox(self.formWidget)
        self.headerCheckbox.setEnabled(False)
        self.headerCheckbox.setChecked(True)
        self.headerCheckbox.setObjectName("headerCheckbox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.headerCheckbox)
        self.verticalLayout_2.addWidget(self.formWidget)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.filePreview = QtWidgets.QTableView(Dialog)
        self.filePreview.setEnabled(False)
        self.filePreview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filePreview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.filePreview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filePreview.setTabKeyNavigation(False)
        self.filePreview.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.filePreview.setGridStyle(QtCore.Qt.DashLine)
        self.filePreview.setObjectName("filePreview")
        self.filePreview.horizontalHeader().setCascadingSectionResizes(True)
        self.filePreview.horizontalHeader().setStretchLastSection(True)
        self.filePreview.verticalHeader().setCascadingSectionResizes(True)
        self.filePreview.verticalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.filePreview, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 7, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setText("")
        icon = QtGui.QIcon.fromTheme("folder")
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName("toolButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.toolButton)
        self.cwdLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.cwdLabel.setFont(font)
        self.cwdLabel.setObjectName("cwdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cwdLabel)
        self.verticalLayout.addWidget(self.groupBox)
        self.fileListView = QtWidgets.QListView(Dialog)
        self.fileListView.setEnabled(False)
        self.fileListView.setDragEnabled(True)
        self.fileListView.setDragDropOverwriteMode(True)
        self.fileListView.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.fileListView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.fileListView.setAlternatingRowColors(True)
        self.fileListView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fileListView.setMovement(QtWidgets.QListView.Snap)
        self.fileListView.setModelColumn(0)
        self.fileListView.setObjectName("fileListView")
        self.verticalLayout.addWidget(self.fileListView)
        self.gridLayout.addLayout(self.verticalLayout, 1, 3, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.editProtocoleBtn = QtWidgets.QPushButton(self.frame)
        self.editProtocoleBtn.setObjectName("editProtocoleBtn")
        self.gridLayout_4.addWidget(self.editProtocoleBtn, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 3, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.toolButton.clicked.connect(Dialog.browse)
        self.fileListView.clicked['QModelIndex'].connect(Dialog.load_csv)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Setup new experiment"))
        self.groupBox_2.setTitle(_translate("Dialog", "Reading options"))
        self.protonLabel.setText(_translate("Dialog", "Proton"))
        self.nitrogenLabel.setText(_translate("Dialog", "Nitrogen"))
        self.residuLabel.setText(_translate("Dialog", "Residues"))
        self.headerCheckbox.setText(_translate("Dialog", "With headers"))
        self.groupBox.setTitle(_translate("Dialog", "Set working directory"))
        self.cwdLabel.setText(_translate("Dialog", "no directory selected"))
        self.label.setText(_translate("Dialog", "Protocole is not set yet."))
        self.editProtocoleBtn.setText(_translate("Dialog", "Edit Protocole"))

